name: rentme_koraput
description: "RentME Koraput - A comprehensive ride-hailing application for Koraput region"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Material Design
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.2.7
  
  # Maps and Location
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  location: ^7.0.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  
  # HTTP and API
  http: ^1.2.2
  dio: ^5.7.0
  crypto: ^3.0.3
  
  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication
  google_sign_in: ^6.2.1
  otpless_flutter: ^2.1.6
  twilio_flutter: ^0.9.0
  sms_autofill: ^2.4.0
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  firebase_ui_auth: ^1.16.1
  firebase_ui_oauth_google: ^1.1.0
  firebase_auth_platform_interface: ^7.4.9
  
  # Supabase
  supabase_flutter: ^2.8.0
  
  # Real-time Communication
  socket_io_client: ^2.0.3+1
  
  # Payment Integration
  razorpay_flutter: ^1.3.7
  
  # Image Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  
  # UI Enhancements
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  
  # Responsive Design
  flutter_screenutil: ^5.9.3
  responsive_framework: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
